"""empty message

Revision ID: 18df970cee7b
Revises: 8c5504d01b00
Create Date: 2020-02-15 14:11:58.577737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18df970cee7b'
down_revision = '8c5504d01b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
