"""empty message

Revision ID: 94409075500d
Revises: 18df970cee7b
Create Date: 2020-02-15 14:16:18.476040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94409075500d'
down_revision = '18df970cee7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
